baseURL = 'https://noriparelius.netlify.app/'
languageCode = 'en-us'
title = 'Being Human'
theme = 'ananke'

#resourceDir = "/resources"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main" # this is for the menu items, all sections are added to main menu, doesn't work for me
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
pluralizelisttitles = true
#posts: /posts/:title/

[[menu.main]]
  name = "Home"
  identifier = "menu.home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  identifier = "menu.blog"
  url = "/post"
  weight = 2

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "dark-gray"
  author = "Nori"
  favicon = ""
  site_logo = "/img/logo.svg"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  date_format = "2. January 2006"
  show_reading_time = true

  # footer items, these are from here https://github.com/LukeSmithxyz/lugo/blob/master/config.toml
  nextprev = true
  showrss = true


