baseURL = 'https://nori-parelius.statichost.eu/'
languageCode = 'en-us'
title = 'Being Human'
theme = 'ananke-nori'

#resourceDir = "/resources"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main" # this is for the menu items, all sections are added to main menu, doesn't work for me
pagination.pagerSize = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
pluralizelisttitles = true
#posts: /posts/:title/
# This next thing is because I set an output for taxonomy
ignoreErrors = ["error-output-taxonomy"]

[[menu.main]]
  name = "Home"
  identifier = "menu.home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  identifier = "menu.posts"
  url = "/post"
  weight = 2

[[menu.main]]
  name = "Fiction"
  identifier = "menu.fiction"	
  url = "/alphabet_superset"
  weight = 3

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["html"]
  section = ["html", "rss"]
  taxonomy = ["html"]


[params]
  text_color = "dark-gray"
  author = "Nori"
  favicon = "/img/favicon.ico"
  site_logo = "/img/logo.svg"
  description = "Nori's blog"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  cover_dimming_class = "bg-black-20"#"bg-transparent"
  cover_dimming_class_page = "bg-black-40"
  recent_posts_number = 3
  date_format = "2. January 2006"
  show_reading_time = true
  Copyright = "Nori Parelius"

  # footer items, these are from here https://github.com/LukeSmithxyz/lugo/blob/master/config.toml
  nextprev = false
  showrss = false

  # default image to show in RSS feed if no featured
  images = ["img/being-human.jpg"]

  # toc
  showtoc = true
  tocopen = false

# socials
[[params.ananke_socials]]
name = "rss"
url = "/post/index.xml"

#[[params.ananke_socials]]
#name = "medium"
#url = "https://medium.com/@nori.parelius"


#[[params.ananke_socials]]
#name = "github"
#url = "https://github.com/nori-parelius"

[[params.ananke_socials]]
name = "tumblr"
url = "https://www.tumblr.com/blog/norisbeinghuman"
color = "#34525f"
label = "Tumblr"

#[[params.ananke_socials]]
#name = "instagram"
#url = "https://www.instagram.com/nori.parelius/"

[[params.ananke_socials]]
name = "bluesky"
url = "https://bsky.app/profile/nori-pareli.bsky.social"
color = "#1185fe"
label = "BlueSky"

[[params.ananke_socials]]
name = "ko-fi"
url = "https://ko-fi.com/noriparelius"
color = "#ff5e5b"
label = "Support me on Ko-fi"


# taxonomies
[taxonomies]
category = 'categories'
tag = 'tags'



